version: '3.5'

services:
  oauthproxy:
    build:
      context: .
      dockerfile: Dockerfile-httpd

  apollo:
    build:
      context: .
      dockerfile: Dockerfile-apollo

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
